name: gexa
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  firebase_core: ^2.30.0
  firebase_database: ^10.4.0 
  firebase_messaging: ^14.7.4
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0
  animate_do: ^3.0.2 
  cloud_firestore: ^4.15.0
  firebase_auth: ^4.17.5
  flutter_svg: ^2.0.7 
  flutter_local_notifications: ^17.0.0 # o la versión más reciente
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.13.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icono_app.png"